name: RideTeleport
main: ridetp\RideTeleport
version: 1.0
api:
 - 3.0.0
 - 3.2.3
load: POSTWORLD
author: vardo

permissions:
  rtp.*:
    default: op
    description: RideTeleportの設定コマンド
    children:
      rtp.command:
        default: op
        description: RideTeleportの設定コマンド